# Generated by Django 4.1.7 on 2023-04-23 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_flag', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField(null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('insta', models.CharField(blank=True, max_length=50)),
                ('telega', models.CharField(blank=True, default='', max_length=50)),
                ('agree_to_private_rule', models.BooleanField(blank=True, default=False)),
                ('bio_check', models.BooleanField(default=False)),
                ('eng_skill', models.CharField(max_length=2)),
                ('languages', models.CharField(max_length=150)),
                ('scholarship', models.BooleanField(default=False)),
                ('eng_class', models.IntegerField(blank=True, default=0)),
                ('math_class', models.IntegerField(blank=True, default=0)),
                ('natural_science_class', models.IntegerField(blank=True, default=0)),
                ('additional_class', models.IntegerField(blank=True, default=0)),
                ('social_science', models.IntegerField(blank=True, default=0)),
                ('additional_courses', models.IntegerField(blank=True, default=0)),
                ('sat', models.BooleanField(default=False)),
                ('act', models.BooleanField(default=False)),
                ('toefl', models.BooleanField(default=False)),
                ('ielts', models.BooleanField(default=False)),
                ('sport', models.CharField(max_length=200)),
                ('ex', models.IntegerField(default=0)),
                ('position', models.CharField(max_length=200)),
                ('sport_org_name', models.CharField(max_length=200)),
                ('sport_org_link', models.CharField(max_length=200)),
                ('highlights_link', models.CharField(blank=True, max_length=200)),
                ('stats_link', models.CharField(blank=True, max_length=200)),
                ('live_stream_link', models.CharField(blank=True, max_length=200)),
                ('pay_or_not', models.BooleanField(default=False)),
                ('hand', models.CharField(blank=True, max_length=10)),
                ('height_inch', models.IntegerField(blank=True, default=0)),
                ('height_cm', models.IntegerField(blank=True, default=0)),
                ('weight_pound', models.IntegerField(blank=True, default=0)),
                ('weight_kg', models.IntegerField(blank=True, default=0)),
                ('league_resolution', models.BooleanField(default=False)),
                ('university_or_club', models.CharField(blank=True, max_length=10)),
                ('national_teem', models.BooleanField(default=False)),
                ('sport_check', models.BooleanField(default=False)),
                ('main_achivment', models.CharField(blank=True, max_length=200)),
                ('letter', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Small_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
