# Generated by Django 4.1.7 on 2023-04-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Univer_Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('univers_name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('telegram', models.CharField(blank=True, default='', max_length=50)),
                ('telegram_id', models.CharField(blank=True, default='', max_length=50)),
                ('count_pos', models.IntegerField(default=0)),
                ('is_un', models.BooleanField(default=True)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('flag', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
